services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marcus7i
    restart: unless-stopped
    ports:
      - "9031:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs