services:
  kizurendev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kizuren/kizuren.dev
    container_name: kizurendev
    restart: unless-stopped
    ports:
      - "9031:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
